#define DEBUG
//#define DEBUG_HARD
//#define GRID_RANDOM
//#define GRID_REFINED
#define LB
#define LB_FLUID
//#define LB_FLUID_INITIAL_KOLMOGOROV 
//#define LB_FLUID_INITIAL_POISEUILLE
#define LB_FLUID_FORCING
#define LB_FLUID_FORCING_POISEUILLE
//#define LB_FLUID_FORCING_KOLMOGOROV
//#define METHOD_EXPONENTIAL
#define METHOD_STEPPING_EULER
//#define METHOD_STEPPING_AB2
#define METHOD_MIXED
#define METHOD_CENTERED
//#define METHOD_UPWIND
#define LB_BC
#define LB_BC_Y
//#define LB_BC_YP_SLIP
//#define LB_BC_YM_SLIP
//#define LB_BC_X
//#define LB_BC_XP_SLIP                                                            
//#define LB_BC_XM_SLIP
//#define LB_BC_XM_INLET
//#define LB_BC_XP_OUTLET
//#define LB_BC_Z
//#define LB_TEMPERATURE
//#define LB_SCALAR
